-- Semilla de catálogos del módulo de mantenimiento de subestaciones (Semana 1, hito H1).
-- Datos extraídos de SUBESTACIONES/Copia de Indicadores de mantenimiento.xlsx (hojas
-- MAESTRO_ESTACIONES, CRONOGRAMA_TABLA_OK, EJECUCION_FORM), no inventados.
--
-- Verificación (checklist del día 1 del plan):
--   SELECT count(*) FROM mant_estacion;                                 -- 23
--   SELECT count(*) FROM mant_actividad WHERE captura_movil_habilitada; -- 9 (CIVIL, alcance MVP)
--   SELECT count(*) FROM mant_programacion WHERE anio = 2026;           -- 309
--   SELECT count(*) FROM mant_elemento WHERE disciplina = 'ELECTRICO';  -- 59 (provisional=TRUE, pendiente depuración R1;
--                                                                            Civil no usa mant_elemento, esto queda listo para cuando eléctrico se retome)

-- 23 estaciones (fuente: SUBESTACIONES/Copia de Indicadores de mantenimiento.xlsx, hoja MAESTRO_ESTACIONES)
INSERT INTO mant_estacion (nombre, tipo, frecuencia_base) VALUES
    ('Ayalas', 'BOMBEO', 'TRIMESTRAL'),
    ('CLAN', 'COMPLEMENTARIA', 'ANUAL'),
    ('Cuche', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren Ayalas', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren chorrito', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren Cuche', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren Duitama', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren Jardines', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren Suescun', 'BOMBEO', 'TRIMESTRAL'),
    ('Dren Tocogua', 'BOMBEO', 'TRIMESTRAL'),
    ('Duitama', 'BOMBEO', 'TRIMESTRAL'),
    ('Fuente Salinas', 'BOMBEO', 'TRIMESTRAL'),
    ('Holanda', 'BOMBEO', 'TRIMESTRAL'),
    ('La Copa', 'COMPLEMENTARIA', 'ANUAL'),
    ('La Playa', 'COMPLEMENTARIA', 'ANUAL'),
    ('Las Vueltas', 'BOMBEO', 'TRIMESTRAL'),
    ('Ministerio', 'BOMBEO', 'TRIMESTRAL'),
    ('Monquira', 'BOMBEO', 'TRIMESTRAL'),
    ('Pantano de Vargas', 'BOMBEO', 'TRIMESTRAL'),
    ('San Rafael', 'BOMBEO', 'TRIMESTRAL'),
    ('Sede Administrativa', 'COMPLEMENTARIA', 'ANUAL'),
    ('Surba', 'BOMBEO', 'TRIMESTRAL'),
    ('Tibasosa', 'BOMBEO', 'TRIMESTRAL');

-- 16 actividades del cronograma 2026, las 3 disciplinas (fuente: hoja CRONOGRAMA_TABLA_OK
-- + el form real para las 2 civiles sin citas de cronograma, ver nota abajo).
-- captura_movil_habilitada = TRUE solo para las 9 de disciplina CIVIL (alcance del MVP,
-- pivote 2026-09-04). ELECTRICO/ELECTROMECANICO quedan en FALSE, en espera.
INSERT INTO mant_actividad (nombre, disciplina, captura_movil_habilitada) VALUES
    ('Corrección hallazgos sede administrativa/ CLAN', 'CIVIL', TRUE),
    ('Ejecución de hallazgos inspección electromecánica', 'ELECTROMECANICO', FALSE),
    ('Inspección eléctrica y electrónica general de Estaciones', 'ELECTRICO', FALSE),
    ('Inspección equipos electromecánicos de Estaciones', 'ELECTROMECANICO', FALSE),
    ('Inspección infraestructura presa La Copa y La Playa', 'CIVIL', TRUE),
    ('Inspección maquinaria amarilla', 'CIVIL', TRUE),
    ('Inspección sede administrativa/ CLAN', 'CIVIL', TRUE),
    ('Inspección vehículos y motocicletas', 'CIVIL', TRUE),
    ('Inspección y arreglo de hallazgos línea MT', 'ELECTRICO', FALSE),
    ('Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)', 'CIVIL', TRUE),
    ('Inspección y mantenimiento compuertas + limpieza pozos succión', 'CIVIL', TRUE),
    ('Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)', 'ELECTRICO', FALSE),
    ('Limpieza subestaciones / verificar tierra / nivel aceite transformador', 'ELECTRICO', FALSE),
    ('Mantenimiento válvulas control bomba y anticipadoras', 'ELECTROMECANICO', FALSE),
    ('Pintura muros Estaciones (segun estado)', 'CIVIL', TRUE),
    ('Pintura puertas/ventanas/barandas Estaciones', 'CIVIL', TRUE);
-- 'Inspección maquinaria amarilla' y 'Inspección vehículos y motocicletas' no tienen
-- citas en CRONOGRAMA_TABLA_OK (0 filas en mant_programacion) pero sí están en el form
-- real como opciones de "Actividad civil" — se siembran como catálogo igual, se
-- capturan por la ruta "actividad no prevista"/ad-hoc, no por cronograma.

-- 59 elementos ELECTRICO: borrador provisional (provisional = TRUE) obtenido partiendo por coma
-- el texto libre de 'Identificacion_Elemento' en la hoja EJECUCION_FORM (228 ejecuciones históricas).
-- provisional hasta la sesión de depuración con el ingeniero (riesgo R1 del plan).
INSERT INTO mant_elemento (nombre, disciplina, provisional) VALUES
    ('Acometida / Red MT', 'ELECTRICO', TRUE),
    ('Arrancador suave', 'ELECTRICO', TRUE),
    ('Arranque', 'ELECTRICO', TRUE),
    ('Bomba', 'ELECTRICO', TRUE),
    ('Bomba de achique', 'ELECTRICO', TRUE),
    ('Bomba de achique 1', 'ELECTRICO', TRUE),
    ('Breaker', 'ELECTRICO', TRUE),
    ('Breaker iluminación interna', 'ELECTRICO', TRUE),
    ('Breaker principal variador', 'ELECTRICO', TRUE),
    ('Cable 350 kcmil 52 m', 'ELECTRICO', TRUE),
    ('Cableado 350 kcmil', 'ELECTRICO', TRUE),
    ('Cableado 500 kcmil y terminales', 'ELECTRICO', TRUE),
    ('Cableado cuarto de bombas', 'ELECTRICO', TRUE),
    ('Cableado potencia bombas', 'ELECTRICO', TRUE),
    ('Cableado y conexiones', 'ELECTRICO', TRUE),
    ('Caja de inspección / pozo / medición', 'ELECTRICO', TRUE),
    ('Cañuelas / Red MT', 'ELECTRICO', TRUE),
    ('Collarines de seguridad', 'ELECTRICO', TRUE),
    ('Contactores', 'ELECTRICO', TRUE),
    ('Fusible de cañuela', 'ELECTRICO', TRUE),
    ('Gabinete de medidores', 'ELECTRICO', TRUE),
    ('Gabinete eléctrico', 'ELECTRICO', TRUE),
    ('Generador VAR', 'ELECTRICO', TRUE),
    ('Inspección y arreglo de hallazgos línea MT', 'ELECTRICO', TRUE),
    ('Levantamiento material hurto', 'ELECTRICO', TRUE),
    ('Luminarias exteriores / cajas', 'ELECTRICO', TRUE),
    ('Luminarias oficinas', 'ELECTRICO', TRUE),
    ('Luminarias postes', 'ELECTRICO', TRUE),
    ('Luminarias solares', 'ELECTRICO', TRUE),
    ('Línea / arranque MT', 'ELECTRICO', TRUE),
    ('Motor eléctrico', 'ELECTRICO', TRUE),
    ('PLC', 'ELECTRICO', TRUE),
    ('PLC / HMI / Variador', 'ELECTRICO', TRUE),
    ('PLC / sistema de control', 'ELECTRICO', TRUE),
    ('PLC estación', 'ELECTRICO', TRUE),
    ('Pararrayos / Transformador', 'ELECTRICO', TRUE),
    ('Poste', 'ELECTRICO', TRUE),
    ('Postes', 'ELECTRICO', TRUE),
    ('Reconectador', 'ELECTRICO', TRUE),
    ('Reconectador MT', 'ELECTRICO', TRUE),
    ('Red media tension', 'ELECTRICO', TRUE),
    ('Relés de protección', 'ELECTRICO', TRUE),
    ('Se aseguran tapas de bandeja control', 'ELECTRICO', TRUE),
    ('Sensores / instrumentación', 'ELECTRICO', TRUE),
    ('Sistema de control', 'ELECTRICO', TRUE),
    ('Sistema de puesta a tierra', 'ELECTRICO', TRUE),
    ('Sub estación', 'ELECTRICO', TRUE),
    ('Subestación', 'ELECTRICO', TRUE),
    ('Subestación / aislamiento / medición', 'ELECTRICO', TRUE),
    ('Toma bifásica 220V', 'ELECTRICO', TRUE),
    ('Tomacorrientes 110V/220V / caja sensor nivel', 'ELECTRICO', TRUE),
    ('Tomacorrientes 110V/220V / reflectores', 'ELECTRICO', TRUE),
    ('Tomacorrientes 110V/220V y cajas', 'ELECTRICO', TRUE),
    ('Transformador', 'ELECTRICO', TRUE),
    ('Transformador / Subestación', 'ELECTRICO', TRUE),
    ('Variador de velocidad', 'ELECTRICO', TRUE),
    ('Vegetación sobre red', 'ELECTRICO', TRUE),
    ('Verificación de tensiones', 'ELECTRICO', TRUE),
    ('iluminacion', 'ELECTRICO', TRUE);

-- 309 citas de programación 2026, las 3 disciplinas (fuente: hoja CRONOGRAMA_TABLA_OK)
INSERT INTO mant_programacion (anio, mes, estacion_id, actividad_id) VALUES
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN JARDINES'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN SUESCUN'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN TOCOGUA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN CHORRITO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CLAN'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SEDE ADMINISTRATIVA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección eléctrica y electrónica general de Estaciones' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN JARDINES'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN SUESCUN'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN TOCOGUA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN CHORRITO'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CLAN'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SEDE ADMINISTRATIVA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza cárcamos / retiro de polvo / ajuste de contactos (gabinetes, bornes)' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Limpieza subestaciones / verificar tierra / nivel aceite transformador' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y arreglo de hallazgos línea MT' AND disciplina = 'ELECTRICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN JARDINES'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN SUESCUN'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN TOCOGUA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN CHORRITO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección equipos electromecánicos de Estaciones' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN JARDINES'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN SUESCUN'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN TOCOGUA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN CHORRITO'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DREN AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Ejecución de hallazgos inspección electromecánica' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Mantenimiento válvulas control bomba y anticipadoras' AND disciplina = 'ELECTROMECANICO')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura puertas/ventanas/barandas Estaciones' AND disciplina = 'CIVIL')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 9, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Pintura muros Estaciones (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 4, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 8, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento cerchas/pasos elevados/limpieza malezas (segun estado)' AND disciplina = 'CIVIL')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 1, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 2, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 3, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SURBA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'HOLANDA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'PANTANO DE VARGAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 10, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'FUENTE SALINAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'DUITAMA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LAS VUELTAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SAN RAFAEL'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 11, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'AYALAS'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CUCHE'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'TIBASOSA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MINISTERIO'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 12, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'MONQUIRA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección y mantenimiento compuertas + limpieza pozos succión' AND disciplina = 'CIVIL')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LA COPA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección infraestructura presa La Copa y La Playa' AND disciplina = 'CIVIL')),
    (2026, 6, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'LA PLAYA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección infraestructura presa La Copa y La Playa' AND disciplina = 'CIVIL')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SEDE ADMINISTRATIVA'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección sede administrativa/ CLAN' AND disciplina = 'CIVIL')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CLAN'), (SELECT id FROM mant_actividad WHERE nombre = 'Inspección sede administrativa/ CLAN' AND disciplina = 'CIVIL')),
    (2026, 5, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'SEDE ADMINISTRATIVA'), (SELECT id FROM mant_actividad WHERE nombre = 'Corrección hallazgos sede administrativa/ CLAN' AND disciplina = 'CIVIL')),
    (2026, 7, (SELECT id FROM mant_estacion WHERE UPPER(nombre) = 'CLAN'), (SELECT id FROM mant_actividad WHERE nombre = 'Corrección hallazgos sede administrativa/ CLAN' AND disciplina = 'CIVIL'));

-- total filas programacion: 309
